### ISSUE TITLE
Feature: Microblog API

### ISSUE THREAD

**Issue by Dayanro** [Dayanro/microblogging#12]
## Epic Title
Feature: Microblog API

### Description
Give users the ability  to create, consult and bookmark  note(s).

### List of Tasks

- [x] Task: Create basic project with test server. #5

- [x] Task: Task: Create a notes model. #6

- [x] Task: Task: Create note #7

- [x] Task: Consult the notes #8

- [x] Task: Retrieve a single note #9

- [x] Task: Bookmark a note #10

- [x] Task: Retrieve the notes marked as favorites #11
