### ISSUE TITLE
Feature: User Authentication 

### ISSUE THREAD

**Issue by Dayanro** [Dayanro/microblogging#4]
## Epic Title
Feature: User Authentication 

### Description
Give users the ability  to access the API.

### List of Tasks

- [x] Task: Create a user model #1

- [x] Task: Create a user model seed #2

- [x] Task: Authentication with username #3
